In [95]:
import re
import unicodedata

import pandas as pd

In [96]:
df = pd.read_csv("../data/raw/batdongsan_com_vn.csv")

In [97]:
def extract_numeric(s:str|None) -> float:
    if not isinstance(s,str) or not s:
        return None

    results = re.search(r"^(\d+.?\d*,?\d*)\D?", s)
    if not results:
        return None
    else:
        num_str = results.group(1)
        num_str = num_str.replace(".","")
        num_str = num_str.replace(",",".")
        return float(num_str)
    
def extract_measuring_unit(s:str|None) -> str:
    if not isinstance(s,str) or not s:
        return None

    results = re.search(r"^\d+.?\d*,?\d*\s*(\D*)", s)
    if not results:
        return None
    else:
        return results.group(1)

In [16]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20855 entries, 0 to 20854
Data columns (total 19 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   price              20853 non-null  object
 1   area               20853 non-null  object
 2   n_bedrooms         10453 non-null  object
 3   n_bathrooms        10091 non-null  object
 4   legal              18290 non-null  object
 5   interior           9524 non-null   object
 6   facing_direction   8622 non-null   object
 7   balcony_direction  4829 non-null   object
 8   front_width        10823 non-null  object
 9   front_road_width   10023 non-null  object
 10  title              20852 non-null  object
 11  description        20851 non-null  object
 12  latitude           20846 non-null  float64
 13  longitude          20846 non-null  float64
 14  verified           20855 non-null  int64
 15  location           20855 non-null  object
 16  location_details   20852 non-null  object
 17  property_type      20855 non-null  object
 18  date_of_posting    20851 non-null  object
dtypes: float64(2), int64(1), object(16)
memory usage: 3.0+ MB

# Extract numerics

Next, we"ll extract numeric values and start inspecting for issues

In [98]:
df["price_val"] = df.price.apply(extract_numeric)
df["price_unit"] = df.price.apply(extract_measuring_unit)
df["area_val"] = df.area.apply(extract_numeric)
df["area_unit"] = df.area.apply(extract_measuring_unit)
df["n_bedrooms"] = df.n_bedrooms.apply(extract_numeric)         # since this overwrite the original, be careful not to run the cell twice
df["n_bathrooms"] = df.n_bathrooms.apply(extract_numeric)
df["front_width_val"] = df.front_width.apply(extract_numeric)
df["front_width_unit"] = df.front_width.apply(extract_measuring_unit)
df["front_road_width_val"] = df.front_road_width.apply(extract_numeric)
df["front_road_width_unit"] = df.front_road_width.apply(extract_measuring_unit)

df[[
    "price_val", "price_unit", "area_val", "area_unit", "n_bedrooms", "n_bathrooms", 
    "front_width_val", "front_width_unit", "front_road_width_val", "front_road_width_unit"
]].describe(include="all")

,price_val,price_unit,area_val,area_unit,n_bedrooms,n_bathrooms,front_width_val,front_width_unit,front_road_width_val,front_road_width_unit
count,18665.000000,18665,20853.000000,20853,10453.000000,10091.000000,10823.000000,10823,10023.000000,10023
unique,NaN,6,NaN,2,NaN,NaN,NaN,1,NaN,1
top,NaN,tỷ,NaN,m²,NaN,NaN,NaN,m,NaN,m
freq,NaN,16250,NaN,20845,NaN,NaN,NaN,10823,NaN,10023
mean,48.201716,NaN,1592.967421,NaN,4.015594,3.744228,37.061121,NaN,14.893263,NaN
std,331.912772,NaN,16022.456873,NaN,7.196456,6.514958,1945.315351,NaN,14.321417,NaN
min,1.000000,NaN,4.800000,NaN,1.000000,1.000000,1.000000,NaN,1.000000,NaN
25%,3.900000,NaN,62.100000,NaN,2.000000,1.000000,5.000000,NaN,7.000000,NaN
50%,9.150000,NaN,100.000000,NaN,3.000000,2.000000,6.000000,NaN,12.000000,NaN
75%,28.000000,NaN,185.000000,NaN,4.000000,4.000000,10.000000,NaN,19.000000,NaN
max,28000.000000,NaN,736000.000000,NaN,250.000000,235.000000,200000.000000,NaN,500.000000,NaN

From this table, there"s 2 noticeable problems:
- The non-null count drops <- "Thỏa thuận" prices got converted None
- 6 unique, non-null `price_unit` -> Price unit inconsistency  

For the first problem, we'll analyze the observations with "Thỏa thuận" prices 
separately and use the rest for the regression model.  
For the second problem, we just need to standardize the units

# Inconsistent price units

In [7]:
df["price_unit"].unique()

array(['tỷ', 'triệu', None, 'triệu/m²', 'nghìn/m²', 'tỷ/m²', 'nghìn'],
      dtype=object)

In [99]:
CONVERSION_MAP = {
    "tỷ": 1000,
    "tỷ/m²": 1000,
    "triệu": 1,
    "triệu/m²": 1,
    "nghìn/m²": 1e-3, 
    "nghìn": 1e-3   
}
def price_to_mil(row, val_col_label:str, unit_col_label:str):
    value = row[val_col_label]
    unit = row[unit_col_label]
    conversion_factor = CONVERSION_MAP.get(unit)
    if value and unit:
        return value * conversion_factor
    else:
        return None

In [100]:
# convert all to million
df["price_val"] = df.apply(price_to_mil, axis=1, args=("price_val","price_unit"))

# convert price per m2 units to full price
price_per_area = df.price_unit.isin(["tỷ/m²", "triệu/m²", "nghìn/m²"])
df.loc[price_per_area, "price_val"] = df.loc[price_per_area, "price_val"] * df.loc[price_per_area, "area_val"]

df[[
    "price_val", "area_val", "n_bedrooms", "n_bathrooms", 
    "front_width_val", "front_road_width_val",
]].describe()

,price_val,area_val,n_bedrooms,n_bathrooms,front_width_val,front_road_width_val
count,1.866500e+04,20853.000000,10453.000000,10091.000000,10823.000000,10023.000000
mean,2.607902e+04,1592.967421,4.015594,3.744228,37.061121,14.893263
std,3.136131e+05,16022.456873,7.196456,6.514958,1945.315351,14.321417
min,3.950000e-03,4.800000,1.000000,1.000000,1.000000,1.000000
25%,3.400000e+03,62.100000,2.000000,1.000000,5.000000,7.000000
50%,7.600000e+03,100.000000,3.000000,2.000000,6.000000,12.000000
75%,1.929600e+04,185.000000,4.000000,4.000000,10.000000,19.000000
max,2.800000e+07,736000.000000,250.000000,235.000000,200000.000000,500.000000

# Extract city

In [101]:
def extract_city(s:str, to_english:bool=False) -> str:
    if not isinstance(s,str) or not s:
        return None
    
    results = re.search(r'.*,(.*$)', s)
    if not results:
        return None
    
    city_vi = results.group(1).strip()
    city_vi = city_vi.replace('.','')
    if to_english:
        city_en = unicodedata.normalize('NFD', city_vi)
        # Remove combining diacritical marks
        city_en = re.sub(r'[\u0300-\u036f]', '', city_en)
        # Replace special Vietnamese letter "đ" and "Đ"
        city_en = city_en.replace('đ', 'd').replace('Đ', 'D')
        return city_en
    else:
        return city_vi

In [102]:
df['city'] = df.location.apply(extract_city)
df[['city', 'location']].sample(5)

              city               location
801    Hồ Chí Minh    Quận 7, Hồ Chí Minh
11155    Quảng Nam    Điện Bàn, Quảng Nam
15457      Đà Nẵng  Ngũ Hành Sơn, Đà Nẵng
1249        Hà Nội        Đống Đa, Hà Nội
6899   Hồ Chí Minh    Nhà Bè, Hồ Chí Minh

# Standardize string/categorical columns

In [22]:
df.city.unique()

array(['Hồ Chí Minh', 'Hà Nội', 'Đà Nẵng', 'Khánh Hòa', 'Bình Dương',
       'Đồng Nai', 'Long An', 'Hòa Bình', 'Hưng Yên', 'Bà Rịa Vũng Tàu',
       'Lâm Đồng', 'Hải Phòng', 'Thanh Hóa', 'Quảng Ngãi', 'Hà Nam',
       'Quảng Ninh', 'Thái Nguyên', 'Tiền Giang', 'Tây Ninh',
       'Kiên Giang', 'Vĩnh Phúc', 'Bắc Ninh', 'Bình Phước', 'Bắc Giang',
       'Đắk Lắk', 'Phú Thọ', 'Nghệ An', 'Gia Lai', 'Ninh Thuận',
       'Thừa Thiên Huế', 'Hải Dương', 'Đắk Nông', 'Bình Thuận', 'Cần Thơ',
       'Ninh Bình', 'Quảng Nam', 'Quảng Bình', 'Bình Định', 'Nam Định',
       'Điện Biên', 'Vĩnh Long', 'Phú Yên', 'Lào Cai', 'Thái Bình',
       'Kon Tum', 'Cà Mau', 'Lạng Sơn', 'Hậu Giang', 'Trà Vinh',
       'Tuyên Quang', 'Yên Bái', 'Đồng Tháp', 'Bến Tre', 'Hà Tĩnh',
       'Bắc Kạn', 'Sóc Trăng', 'An Giang', 'Quảng Trị', 'Sơn La'],
      dtype=object)

In [23]:
df.legal.unique()

array(['Sổ hồng đầy đủ', 'Hợp đồng mua bán', 'HDMB', 'Sổ đỏ/ Sổ hồng',
       'Hợp đồng mua bán.', 'Sổ đỏ/ Sổ hồng.', 'HĐMB', 'Sổ đỏ', nan,
       'Sổ hồng', 'Sổ hồng riêng', 'Có sổ.',
       'Sổ hồng đã hoàn công năm 2025', 'Đã có sổ đỏ.', 'Sổ đỏ.',
       'Đã có sổ', 'Sổ hồng (sử dụng chung).', 'Đang chờ sổ',
       'Bùi Xương Trạch, khương đình, Thanh Xuân.',
       'Đã có sổ đỏ - mua bán vi bằng',
       'Sổ đỏ chính chủ, sẵn sàng giao dịch.', 'Sổ hồng.', 'Có sổ',
       'Sổ hồng lâu dài', 'Bìa đỏ chính chủ.', 'Sổ đỏ/ Sổ hồng sdc',
       'Sổ đỏ/ Sổ hồng đất trồng cây', 'Sổ đỏ/ Sổ hồng chung',
       'Đã có sổ riêng', 'Sổ hồng 50 năm.', 'Có sổ( sử dụng chung).',
       'Sổ hồng vĩnh viễn.', 'Sổ đỏ/ Sổ hồng', 'Pháp lý: Sổ cá nhân.',
       'Sổ đỏ 50 năm', 'Mua bán công chứng vi bằng', 'Nhà đã có sổ đỏ.',
       'Có sổ đỏ.', 'Sổ đỏ lâu dài.', 'Sổ đỏ/sổ hồng', 'Đang chờ sổ.',
       'Giầy tờ pháp lý đầy đủ', 'sổ đỏ sang tên', 'Sổ đỏ chính chủ',
       'Hợp đồng mua bán vi bằng', 'Sổ hồng riêng.',
       'TRUNG TÂM THƯƠNG MẠI MẶT BIỂN LỚN NHẤT MIỀN NAM!',
       'Hợp đồng thuê kiot 50 năm, sang tên thế quyền thuê', 'Sổ chung',
       'Đã có sổ đỏ', 'Sổ đỏ sang tên.', 'Sổ đỏ sang tên',
       'Pháp lý: Giao dịch vi bằng, thủ tục nhanh gọn.', 'Sổ đỏ đầy đủ',
       '- Sổ đỏ chính chủ.', 'Giấy tờ đất pháp lý rõ ràng.', 'HĐ vi bằng',
       'Mỗi căn hộ có 1 bìa hồng. Mua bán lập HĐ vi bằng.',
       'Sổ đỏ chính chủ, sang tên nhanh.', 'Sở hữu 70 năm',
       'Thoả thuận nguyên tắc', 'Sổ + giấy phép xây dựng.',
       'Sổ đỏ/ Sổ hồng ( sử dụng chung)', 'Sở hữu lâu dài', 'SỔ HỒNG',
       'Sổ hồng sdc', 'Sổ đỏ lâu dài sẵn sàng giao dịch ngay.',
       'Sổ đỏ/ Sổ hồng (sử dụng chung)',
       'Sổ đỏ/ Sổ hồng ( sử dụng chung)', 'HĐMB.',
       'Sổ đỏ/ Sổ hồng ĐSH phôi riêng', 'Sổ đỏ/ Sổ hồng ĐSH',
       'Có sổ đồng sở hữu cả toà. Mua bán ký vi bằng.',
       '- Sổ hồng chính chủ.', 'Sổ hồng cá nhân',
       'Có sổ. ( sử dụng chung)', 'Sổ hồng riêng hoàn công',
       'Sổ hoàn công đầy đủ', 'Sổ hồng chính chủ.', 'Sổ đỏ/sổ hồng.',
       'Sổ đỏ/ Sổ hồng đồng sh', 'Pháp lý lâu dài',
       'Sổ đỏ/ Sổ hồng( sử dụng chung)', 'Hợp đồng thuê nhà ở dài hạn',
       'Sổ đồng SH', 'Sở hữu lâu dài- vĩnh viển', 'hợp đồng 50 năm',
       'Sổ đỏ lâu dài: Đảm bảo quyền sở hữu và giá trị tài sản bền vững.',
       'Sở hữu riêng, sổ đỏ lâu dài.', 'Sổ hồng 50 năm/hợp đồng mua bán',
       'Sổ hồng riêng, sang tên nhanh chóng.',
       'Giấy Tờ Giao Khoán 01 Của Nông Trường Việt Mông',
       'Sổ hồng 50 năm', 'Sổ CDT, xây nhà ra hoàn công ra tên',
       'HDMB nhà ở hình thành trong tương lai', 'HĐMb',
       'Có sổ ( sử dụng chung)', 'Số hồng', 'Sổ hồng riêng',
       'Sổ đỏ/ sổ hồng', 'Sổ Hồng', 'Sổ đỏ chính chủ.',
       'Hợp đồng mua bán Sổ đỏ lâu dài',
       'Sổ đỏ/ Sổ hồng (sử dụng chung).', 'Sổ hồng lâu dài.',
       'Sổ hồng cá nhân giao dịch nhanh gọn.', 'Đầy đủ',
       'Đang chờ sổ, mua bán vi bằng', 'HDMB.', 'Chính chủ rõ ràng',
       'Sẵn sổ.', 'Pháp lý: Sổ hồng vĩnh viễn.',
       'Sổ đỏ chính chủ/ Sổ hồng', 'Sổ đỏ/Sổ hồng', 'Hợp đồng góp vốn',
       'Đầy đủ pháp lý', 'Đất trồng cây lâu năm', 'Đã có sổ hồng.',
       'Có sổ sẵn.', 'Chủ trương Cụm Công Nghiệp', 'Lâu dài',
       'Chờ cấp sổ', 'Sổ hồng riêng. Hoàn công', 'Sổ riêng.',
       'Hợp đồng đặt cọc', 'Đã có HĐMB.', 'Sổ đỏ cc', 'Sổ đỏ lâu dài',
       'Pháp lý (đã có sổ đỏ từ lô).', 'Sổ hồng:', '100% đất ở đô thị',
       'Đã có sổ đỏ từng lô thổ cư 100%.', 'Sổ hồng- Full thổ', 'VBTT',
       'Số 90', 'Hợp đồng mua bán Sổ đỏ sở hữu lâu dài.',
       'Sổ hồng sẵn công chứng.', 'Hợp đồng', 'Đã có hợp đồng mua bán',
       'Pháp lý chuẩn', 'Sổ hồng riêng, công chứng sang tên nhanh.',
       'Đã có sổ.', 'Sổ sẵn công chứng.', 'Sổ hồng/ sổ đỏ',
       'Sổ đỏ riêng, sang tên nhanh.', 'Có sổ hồng',
       '- Chờ có sổ đỏ DT 100m², các DT còn lại đã có sổ đỏ.',
       'Sổ hồng đầy đủ.', 'Bằng Khoán Điền Thổ',
       'Đất sổ đỏ - tự xây dựng (đã cấp sổ đỏ ở giai đoạn 1).',
       'Sổ riêng',
       'Sổ hồng riêng, đất khu công nghiệp, đã đóng thuế 50 năm 1 lần.',
       'Pháp lý rõ ràng, sẵn sàng giao dịch.', 'Sổ đỏ/ sổ hồng.',
       'Sổ hồng vuông vức.',
       '- Sổ đỏ vuông đẹp, cất két đợi đón chủ mới.', 'Đầy đủ sổ',
       'Mua - Nhận ngay lợi nhuận lên đến 7%/năm Vốn ban đầu chỉ bỏ ra 30% căn hộ, nhận cam kết lợi nhuận ngay lên đến 7%/Năm (Đã có HĐ Thuê 5 năm) Diện tích: 439,5/416,5m² bao gồm 1 Trệt 1 Lầu Bàn giao thô, hoàn thiện mặt ngoài full kính Gamuda Land cam kết th',
       'Pháp lý sở hữu lâu dài.', 'Sổ sẵn.', 'SĐ', 'Sổ đầy đủ',
       'Đất 50 năm cấp từ năm 2010 đến 2060', 'Giao dịch vi bằng',
       'Sổ đỏ trao tay', '- Pháp lý đầy đủ, ngân hàng hỗ trợ vay 75%.',
       'Sổ hồng hoàn công.', 'Sổ hoàn công đầy đủ.',
       '- Sổ hồng riêng từng căn, sở hữu lâu dài.', 'Sổ cá nhân',
       'Đang booking', 'Số đỏ', 'sổ hồng', 'Sổ hồng trao tay.', 'Hđ htđt',
       'Pháp lý hoàn chỉnh, giao dịch ngay trong 1 nốt nhạc.',
       'Pháp lý đang chờ sổ', 'Bàn giao nhà 3 tháng có sổ',
       'Pháp lý chuẩn.', 'HĐ góp Vốn', 'Sỏ đỏ/sổ hồng',
       'Sổ đỏ lâu dài + Quỹ căn HĐMB 50 năm', '+ Sổ đỏ',
       'Sổ hồng chính chủ', 'Pháp lý cá nhân.',
       'Pháp lý minh bạch, sang tên công chứng nhanh chóng.',
       'Sổ đã lên full SKC hoàn công trên sổ.', 'Mua bán vi bằng',
       'Sổ hồng đầy đủ, công chứng sang tên ngay.',
       'Sổ đỏ/ Sổ hồng đất trồng cây.', 'Sổ đỏ/ Sổ hồng đất HNK', 'SHR',
       'TMDV sở hữu lâu dài', 'Sổ đỏ/ Sổ hồng(chung).',
       'Sổ hồng chính chủ vĩnh viễn.', 'VBTT.', 'Sổ đỏ đầy đủ.',
       'Giấy phép xây dựng đầy đủ', 'Sổ đỏ vĩnh viễn', 'Pháp lý đầy đủ',
       'Sổ hồng cá nhân.', 'Sổ đỏ chính chủ, sang tên nhanh gọn',
       'Hợp Đồng Mua Bán', '- Pháp lý cá nhân.',
       'Sổ đỏ chính chủ, pháp lý minh bạch',
       '- Pháp lý đã có sổ (lâu dài).', 'Văn Bản Thoã Thuận',
       'Sổ đỏ/sổ hồng (SDC).', 'Pháp lý rõ ràng',
       'Hợp đồng mua bán, sổ đỏ tên cty.',
       'Hợp đồng mua bán và sổ đỏ tên công ty', 'Sổ đỏ/ Sổ hồng(SDC).',
       'Sổ đỏ nở hậu, phong thuỷ đẹp, sang tên nhanh.', 'Có.',
       'Hợp đồng đặt cọc.', 'hợp đồng đặt cọc',
       'Sổ đỏ chính chủ sang tên ngay.', 'Hợp Đồng Góp Vốn',
       'Phiếu giữ chỗ',
       '+ Pháp lý hiện tại tất cả các căn hộ đều đang là HĐMB.',
       'Pháp lý: Sổ hồng bàn giao, công chứng HĐMB sang tên ngay.',
       'Sổ đỏ/ Sổ hồng(chung)', 'Sổ hồng riêng từng lô',
       'Sổ hồng chung, mua bán vi bằng', 'Khu 5', 'Văn bản thỏa thuận',
       'Trích lục có xác nhận chính quyền đia phương', 'Sỡ hữu lâu dài',
       'Sổ đỏ chính chủ sẵn sàng giao dịch.', 'Vi bằng', 'Sổ hồng chung',
       '- Sổ đỏ vuông đẹp, giao dịch ngay.', 'Vi bằng, hs xã',
       'Sổ hồng riêng cá nhân.',
       'Dự án pháp lý sổ hồng từng căn, sẵn slot ô tô dưới hầm.',
       '- Pháp lý: Đầy đủ, ký HĐMB trực tiếp với chủ đầu tư ngay.',
       'Đã có sổ đỏ từng lô', 'Sẵn sổ giao dịch ngay',
       'Sổ đỏ sẵn sàng giao dịch', 'Vinhomes green paradise cần giờ',
       'Sổ đỏ pháp lý rõ ràng', 'Sổ hồng trao tay',
       'Sổ đỏ/ Sổ hồng(sử dung chung).', 'Có sổ hồng.',
       'Sổ đỏ chính chủ, sang tên ngay.',
       'Hợp đồng mua bán (đã có sổ hồng từng căn)', 'Một sổ chính chủ',
       'Hợp đồng với công ty.', 'Hợp đồng với công ty xây nhà ra sổ.',
       'Sổ đỏ chính chủ, vuông đẹp.',
       'Bán căn góc 2 mặt tiền Panoma 2 - Sở hữu lâu dài - Tiềm năng vượt trội',
       'Sổ sẵn', 'Chuyển nhượng bằng HĐMB (đã có sổ từng lô).',
       'Đã có sổ đỏ chính chủ.', '16 - 18', 'Bìa đỏ pháp lý rõ ràng.',
       '- Sổ đỏ chính chủ mua bán nhanh gọn.'], dtype=object)

In [103]:
def standardize_legal_doc_types(s: str) -> str:
    if not s or not isinstance(s, str) or not s.strip():
        return None
    
    s = s.lower().strip()

    if re.search(r'sổ đỏ', s) or re.search(r'sđ', s) or re.search(r'bìa đỏ',s):
        if re.search(r'sổ hồng', s) or re.search(r'bìa hồng',s): 
            return 'Giấy tờ hợp lệ'
        return 'Sổ đỏ'
    if re.search(r'sổ hồng', s) or re.search(r'bìa hồng', s):
        return 'Sổ hồng'
    if re.search(r'chờ sổ', s):
        return 'Đang chờ sổ'
    if re.search(r'/', s) or re.search(r'sổ', s) or re.search(r'có số', s) or re.search(r'giấy tờ',s) or re.search(r'pháp l[íý]:? đầy đủ|đầy đủ pháp l[íý]|pháp l[íý] chuẩn|pháp l[íý] rõ ràng',s) or re.search(r'bằng khoán',s):
        return 'Giấy tờ hợp lệ'
    if re.search(r'hợp đồng mua bán|hđmb|hdmb|hợp đồng|hd|hđ', s) or re.search(r'vi bằng|vb', s) or re.search(r'văn bản thõa thuận',s):
        return 'Hợp đồng mua bán'
    if re.search(r'giấy tờ giao khoán', s) or re.search(r'giấy phép', s) or re.search(r'trích lục', s):
        return 'Giấy tờ khác'
    return None

In [104]:
df['legal_docs'] = df.legal.apply(standardize_legal_doc_types)
df[['legal_docs', 'legal']].sample(5)

           legal_docs                                              legal
3876   Giấy tờ hợp lệ                                    Sổ đỏ/ Sổ hồng.
9794   Giấy tờ hợp lệ  Mua - Nhận ngay lợi nhuận lên đến 7%/năm Vốn b...
16727  Giấy tờ hợp lệ                                     Sổ đỏ/ Sổ hồng
15238            None                                                NaN
5943   Giấy tờ hợp lệ                                     Sổ đỏ/ Sổ hồng

In [91]:
df[['legal_docs', 'legal']].sample(5)

           legal_docs           legal
10090  Giấy tờ hợp lệ  Sổ đỏ/ Sổ hồng
2378   Giấy tờ hợp lệ  Sổ đỏ/ Sổ hồng
16438            None             NaN
15026  Giấy tờ hợp lệ  Sổ đỏ/ Sổ hồng
3631   Giấy tờ hợp lệ  Sổ đỏ/ Sổ hồng

# Select columns for analysis

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20855 entries, 0 to 20854
Data columns (total 29 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   price                  20853 non-null  object
 1   area                   20853 non-null  object
 2   n_bedrooms             10453 non-null  float64
 3   n_bathrooms            10091 non-null  float64
 4   legal                  18290 non-null  object
 5   interior               9524 non-null   object
 6   facing_direction       8622 non-null   object
 7   balcony_direction      4829 non-null   object
 8   front_width            10823 non-null  object
 9   front_road_width       10023 non-null  object
 10  title                  20852 non-null  object
 11  description            20851 non-null  object
 12  latitude               20846 non-null  float64
 13  longitude              20846 non-null  float64
 14  verified               20855 non-null  int64
 15  location               20855 non-null  object
 16  location_details       20852 non-null  object
 17  property_type          20855 non-null  object
 18  date_of_posting        20851 non-null  object
 19  price_val              18665 non-null  float64
 20  price_unit             18665 non-null  object
 21  area_val               20853 non-null  float64
 22  area_unit              20853 non-null  object
 23  front_width_val        10823 non-null  float64
 24  front_width_unit       10823 non-null  object
 25  front_road_width_val   10023 non-null  float64
 26  front_road_width_unit  10023 non-null  object
 27  city                   20855 non-null  object
 28  legal_docs             18238 non-null  object
dtypes: float64(8), int64(1), object(20)
memory usage: 4.6+ MB

In [110]:
cols_for_analysis = [
    # highly relevant for analysis
    'price_val', 'area_val', 'n_bedrooms', 'n_bathrooms', 'front_width_val', 'front_road_width_val',
    'legal_docs', 'facing_direction', 'balcony_direction', 'property_type', 'city', 'location', # location -> addr

    # might be useful, just not now
    'latitude', 'longitude', 'title', 'description', 'location_details', 'date_of_posting', 'interior', 'verified'
]
df_pruned = df[cols_for_analysis]
df_pruned = df_pruned.rename({
    'price_val': 'price',
    'area_val':'area',
    'front_width_val':'front_width',
    'front_road_width_val':'front_road_width',
    'city':'city/district',
    'location_details':'address_details',
    'location': 'address',
}, axis=1)
df_pruned.sample(3)

,price,area,n_bedrooms,n_bathrooms,front_width,front_road_width,legal_docs,facing_direction,balcony_direction,property_type,city/district,address,latitude,longitude,title,description,address_details,date_of_posting,interior,verified
17246,8100.0,99.0,NaN,NaN,5.2,20.0,Giấy tờ hợp lệ,Bắc,NaN,Đất nền dự án,Hồ Chí Minh,"Quận 9, Hồ Chí Minh",10.799038,106.827740,Bán đất nền đường 20 dự án Centana City Điền P...,"Tọa lạc tại Centana City Điền Phúc Thành, Đườn...","Dự án Centana City Điền Phúc Thành, Đường Trườ...",04/10/2025,NaN,0
18455,5200.0,35.0,3.0,4.0,4.0,NaN,Giấy tờ hợp lệ,Đông - Nam,NaN,Nhà riêng,Hà Nội,"Hoài Đức, Hà Nội",21.048791,105.704305,Siêu phẩm nhà 5 tầng phố Yên Bệ Hoài Đức Hà Nộ...,"Bán nhà phố Yên Bệ Kim Chung Hoài Đức Hà Nội, ...","Đường Yên Bệ, Xã Kim Chung, Hoài Đức, Hà Nội",30/09/2025,NaN,0
13367,6600.0,70.0,NaN,NaN,6.0,5.0,Giấy tờ hợp lệ,NaN,NaN,"Shophouse, nhà phố thương mại",Hà Nội,"Hoàng Mai, Hà Nội",20.958746,105.846133,Shophouse tầng 1 - lô góc - chân đế chung cư G...,Shophouse tầng 1 - lô góc - chân đế chung cư G...,"Green Park Trần Thủ Độ, số 1, Đường Trần Thủ Đ...",02/10/2025,Không nội thất,0

In [111]:
df_pruned.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20855 entries, 0 to 20854
Data columns (total 20 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   price              18665 non-null  float64
 1   area               20853 non-null  float64
 2   n_bedrooms         10453 non-null  float64
 3   n_bathrooms        10091 non-null  float64
 4   front_width        10823 non-null  float64
 5   front_road_width   10023 non-null  float64
 6   legal_docs         18246 non-null  object
 7   facing_direction   8622 non-null   object
 8   balcony_direction  4829 non-null   object
 9   property_type      20855 non-null  object
 10  city/district      20855 non-null  object
 11  address            20855 non-null  object
 12  latitude           20846 non-null  float64
 13  longitude          20846 non-null  float64
 14  title              20852 non-null  object
 15  description        20851 non-null  object
 16  address_details    20852 non-null  object
 17  date_of_posting    20851 non-null  object
 18  interior           9524 non-null   object
 19  verified           20855 non-null  int64
dtypes: float64(8), int64(1), object(11)
memory usage: 3.2+ MB

In [112]:
df_pruned.to_csv('../data/interim/batdongsan_com_vn(1).csv')